Add note about CodeDeployToECS-incompatible ZIP files
ZIP files that use the combination of streaming input and the store
(uncompressed) archiving method, will make the CodeDeployToECS action
return an error:

  Exception while trying to read the task definition artifact file from: <source artifact name>

This error is identical to the one prompted by exceeding the maximum
compressed artifact size limit of 3 MB.

ZIP files that use streaming input will put file entry metadata after
writing the file body (compressed or not, depending on method). When
using the store archiving method, there may be ambiguity around whether
the complete body is present. The deflate method does not have this
problem, since this information is encoded into the deflate format. Some
ZIP implementations, notably java.util.zip, do not support this
combination, and will throw an exception. For example:

  java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
    at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:311)
    at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:123)

Related links:
  https://github.com/aws/containers-roadmap/issues/1112
  https://bugs.openjdk.java.net/browse/JDK-8143613
  https://stackoverflow.com/questions/47208272/android-zipinputstream-only-deflated-entries-can-have-ext-descriptor